### ISSUE TITLE
TypeError: no implicit conversion of Array into String

### ISSUE THREAD

**Issue by Jalle19** [capistrano-plugins/capistrano-ssh-doctor#6]
I'm getting this as soon as I run the command:

```
$ cap production ssh:doctor
(Backtrace restricted to imported tasks)
cap aborted!
TypeError: no implicit conversion of Array into String

Tasks: TOP => ssh:local:private_key_exists
(See full trace by running task with --trace)
```

Trace output:

```
$ cap production ssh:doctor --trace
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke ssh:doctor (first_time)
** Execute ssh:doctor
** Invoke ssh:config:git (first_time)
** Execute ssh:config:git
** Invoke ssh:config:repo_url (first_time)
** Execute ssh:config:repo_url
** Invoke ssh:config:password (first_time)
** Execute ssh:config:password
** Invoke ssh:config:agent_forwarding (first_time)
** Execute ssh:config:agent_forwarding
** Invoke ssh:local:private_key_exists (first_time)
** Execute ssh:local:private_key_exists
cap aborted!
TypeError: no implicit conversion of Array into String
/var/lib/gems/2.3.0/gems/capistrano-ssh-doctor-1.0.0/lib/capistrano/tasks/ssh_doctor.rake:53:in `exists?'
/var/lib/gems/2.3.0/gems/capistrano-ssh-doctor-1.0.0/lib/capistrano/tasks/ssh_doctor.rake:53:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/2.3.0/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:16:in `invoke'
/var/lib/gems/2.3.0/gems/capistrano-ssh-doctor-1.0.0/lib/capistrano/tasks/ssh_doctor.rake:112:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/var/lib/gems/2.3.0/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in `run'
/var/lib/gems/2.3.0/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
/usr/local/bin/cap:23:in `load'
/usr/local/bin/cap:23:in `<main>'
Tasks: TOP => ssh:local:private_key_exists
```

**Comment by efrence** [comment]
any update on this?.

**Comment by henscu** [comment]
I'm getting the same error. Any progress on this?
